//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_baiviethuongdandangkythanhvien
    {
        public int id { get; set; }
        public string tenbaiviethuongdan { get; set; }
        public string noidungbaiviet { get; set; }
        public string tenbaiviethuongdanen { get; set; }
        public string noidungbaivieten { get; set; }
    }
}
