//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class banhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public banhang()
        {
            this.chitietdonhangs = new HashSet<chitietdonhang>();
        }
    
        public int id { get; set; }
        public string madonbanhang { get; set; }
        public Nullable<int> tongtien { get; set; }
        public string tenKH { get; set; }
        public string diachiKH { get; set; }
        public string dienthoaiKH { get; set; }
        public string ghichu { get; set; }
        public Nullable<int> trangthaidonhang { get; set; }
        public Nullable<System.DateTime> ngaydathang { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietdonhang> chitietdonhangs { get; set; }
    }
}
