//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietdonhang
    {
        public int id { get; set; }
        public Nullable<int> iddonbanhang { get; set; }
        public string idsp { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<int> giaban { get; set; }
        public string tensanpham { get; set; }
    
        public virtual banhang banhang { get; set; }
        public virtual sanpham sanpham { get; set; }
    }
}
