//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnhChoChuDe
    {
        public int id { get; set; }
        public string imgName { get; set; }
        public string imgUrl { get; set; }
        public Nullable<int> loaihinhanh { get; set; }
    
        public virtual admin_loaihinhanh admin_loaihinhanh { get; set; }
    }
}
